# -*- coding: utf-8 -*-
# select one user from SelectUserWithTweet

# input1: SelectUserWithTweet    # generated by TwitterFacebookData2017\01SelectUser
# userID	screen	lang	Follower	Friend	Favourite	Status	List	CreatedAt	UtcOffset	TimeZone
# 15074406	junkdiver	ja	214	158	339	88872	30	2008-06-10 15:59:07	32400	Tokyo
# 0              1      2        3              4       5               6       7       8                9               10

# output: SelectUserOne
# userID	screen	lang	Follower	Friend	Favourite	Status	List	CreatedAt	UtcOffset	TimeZone
# 15074406	junkdiver	ja	214	158	339	88872	30	2008-06-10 15:59:07	32400	Tokyo
# 0              1      2        3              4       5               6       7       8                9               10


import datetime
import time
import sys
import os


def printTime(beginTime):
    endTime = datetime.datetime.now() #calculate time
    print ("------------consumed-----------time-----------begin-----------")
    print ("consumed time:" + str(endTime - beginTime) )
    print ("------------consumed-----------time-----------end-------------")


def readSelectUsers(inFile1,txtNumber,outFile):
    fin = open(inFile1) 
    fout = open(outFile,'w')
    
    try:
        fstartFile = open(txtNumber)
    except:
        foutTemp = open(txtNumber,'w')
        foutTemp.write(str('0'))
        foutTemp.close()
        fstartFile = open(txtNumber)         
    startNumber = int(fstartFile.read()) + 1



    count =0
    for current in fin:
        count += 1
        if( count ==  startNumber):
            fout.write(current)
            break
    fout.close()
    fin.close()
    
    fstartFile.close()
    foutTemp = open(txtNumber,'w')
    foutTemp.write(str(count))
    foutTemp.close()    

def main(argv):
    inFile1 = argv[1]  # SelectUserWithTweet
    outFile1 = argv[2]  # SelectUserOneNum    # record current the line of currently selected user 
    outFile = argv[3]  # SelectUserOne
    
    reload(sys)
    sys.setdefaultencoding('utf-8')
    beginTime = datetime.datetime.now() 
    
    txtNumber = outFile1 # 'GenerateUserTendUrlOneNum'
    readSelectUsers(inFile1, txtNumber,outFile)
    
    
    #printTime(beginTime)       
    #print "\a"
    #print 'finish' 

    
if __name__ == "__main__":
    #ִmain fuction
    main(sys.argv)
